//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.10 at 11:13:42 AM IST 
//
package Infra;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Debug">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="logDir" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="DebugMode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OpenCV">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="DebugByID" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="SamplingInterval" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Lessons">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="PdfStore" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "debug",
    "openCV",
    "lessons"
})
@XmlRootElement(name = "Configuration")
public class Configuration {

    @XmlElement(name = "Debug", required = true)
    protected Configuration.Debug debug;
    @XmlElement(name = "OpenCV", required = true)
    protected Configuration.OpenCV openCV;
    @XmlElement(name = "Lessons", required = true)
    protected Configuration.Lessons lessons;

    /**
     * Gets the value of the debug property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration.Debug }
     *     
     */
    public Configuration.Debug getDebug() {
        return debug;
    }

    /**
     * Sets the value of the debug property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration.Debug }
     *     
     */
    public void setDebug(Configuration.Debug value) {
        this.debug = value;
    }

    /**
     * Gets the value of the openCV property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration.OpenCV }
     *     
     */
    public Configuration.OpenCV getOpenCV() {
        return openCV;
    }

    /**
     * Sets the value of the openCV property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration.OpenCV }
     *     
     */
    public void setOpenCV(Configuration.OpenCV value) {
        this.openCV = value;
    }

    /**
     * Gets the value of the lessons property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration.Lessons }
     *     
     */
    public Configuration.Lessons getLessons() {
        return lessons;
    }

    /**
     * Sets the value of the lessons property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration.Lessons }
     *     
     */
    public void setLessons(Configuration.Lessons value) {
        this.lessons = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="logDir" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="DebugMode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Debug {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "logDir")
        protected String logDir;
        @XmlAttribute(name = "DebugMode")
        protected String debugMode;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the logDir property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLogDir() {
            return logDir;
        }

        /**
         * Sets the value of the logDir property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLogDir(String value) {
            this.logDir = value;
        }

        /**
         * Gets the value of the debugMode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDebugMode() {
            return debugMode;
        }

        /**
         * Sets the value of the debugMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDebugMode(String value) {
            this.debugMode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="PdfStore" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Lessons {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "PdfStore")
        protected String pdfStore;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the pdfStore property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPdfStore() {
            return pdfStore;
        }

        /**
         * Sets the value of the pdfStore property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPdfStore(String value) {
            this.pdfStore = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="DebugByID" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="SamplingInterval" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class OpenCV {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "DebugByID")
        protected Short debugByID;
        @XmlAttribute(name = "SamplingInterval")
        protected Byte samplingInterval;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the debugByID property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getDebugByID() {
            return debugByID;
        }

        /**
         * Sets the value of the debugByID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setDebugByID(Short value) {
            this.debugByID = value;
        }

        /**
         * Gets the value of the samplingInterval property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getSamplingInterval() {
            return samplingInterval;
        }

        /**
         * Sets the value of the samplingInterval property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setSamplingInterval(Byte value) {
            this.samplingInterval = value;
        }

    }

}
