//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.12 at 02:29:08 PM IST 
//


package Infra;

import java.math.BigInteger;


public class Configuration
{
    private Debug Debug;

    public Debug getDebug() { return this.Debug; }

    public void setDebug(Debug Debug) { this.Debug = Debug; }

    private OpenCV OpenCV;

    public OpenCV getOpenCV() { return this.OpenCV; }

    public void setOpenCV(OpenCV OpenCV) { this.OpenCV = OpenCV; }

    private Lessons Lessons;

    public Lessons getLessons() { return this.Lessons; }

    public void setLessons(Lessons Lessons) { this.Lessons = Lessons; }

    public static class Lessons
    {
        private String PdfStore;

        public String getPdfStore() { return this.PdfStore; }

        public void setPdfStore(String PdfStore) { this.PdfStore = PdfStore; }
    }

    public static class OpenCV
    {
        private long DebugByID;

        public long getDebugByID() { return this.DebugByID; }

        public void setDebugByID(long DebugByID) { this.DebugByID = DebugByID; }

        private int SamplingInterval;

        public int getSamplingInterval() { return this.SamplingInterval; }

        public void setSamplingInterval(int SamplingInterval) { this.SamplingInterval = SamplingInterval; }
    }

    public static class Debug
    {
        private String logDir;

        public String getLogDir() { return this.logDir; }

        public void setLogDir(String logDir) { this.logDir = logDir; }

        private boolean DebugMode;

        public boolean getDebugMode() { return this.DebugMode; }

        public void setDebugMode(boolean DebugMode) { this.DebugMode = DebugMode; }
    }
}
